dist: xenial
sudo: false
language: cpp

before_install:
  - pip install --user cpp-coveralls


script:
  - cmake . -DCOVERAGE=1
  - cmake --build .
  - ./Tests

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"